{{- if and .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-proxyserver
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: proxyserver
    - port: 8092
      targetPort: 8092
      protocol: TCP
      name: health
    - port: 8093
      targetPort: 8093
      protocol: TCP
      name: admin
  selector:
    app: konnectivity-server

---
# agent connect's server
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-agentserver
spec:
  type: ClusterIP
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: agentserver
  selector:
    app: konnectivity-server
{{- end }}
